"use client";

import { useState } from "react";
import { resolveMessageReport } from "@/app/actions/admin/message-reports";
import { Flag, Search } from "lucide-react";

type Report = { id: string; reason: string; status: string; createdAt: string; conversationId: string; content: string; messageCreatedAt: string; reporterName: string; senderName: string };
export default function MessageReportsClient({ reports: initialReports }: { reports: Report[] }) {
  const [reports, setReports] = useState(initialReports); const [search, setSearch] = useState("");
  const visible = reports.filter(report => `${report.reason} ${report.content} ${report.senderName} ${report.reporterName}`.toLowerCase().includes(search.toLowerCase()));
  const resolve = async (id: string) => { const result = await resolveMessageReport(id); if (result.success) setReports(current => current.map(report => report.id === id ? { ...report, status: "resolved" } : report)); };
  return <div className="mx-auto max-w-6xl"><div className="mb-8"><h2 className="text-2xl font-bold text-heading">Message reports</h2><p className="mt-1 text-body">Review flagged messages and preserve the original evidence.</p></div><div className="relative mb-5 max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search reports" className="w-full rounded-lg border border-border bg-surface py-2 pl-9 pr-3 text-sm text-heading outline-none" /></div><div className="space-y-4">{visible.length ? visible.map(report => <article key={report.id} className="rounded-xl border border-border bg-surface p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 font-bold text-heading"><Flag className="h-4 w-4 text-error" />Reported message from {report.senderName}</p><p className="mt-1 text-xs text-muted">Reported by {report.reporterName} · {new Date(report.createdAt).toLocaleString()}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${report.status === "open" ? "bg-error/10 text-error" : "bg-success/10 text-success"}`}>{report.status}</span></div><p className="mt-4 rounded-lg border-l-2 border-error bg-surface-secondary p-3 text-sm text-heading">{report.content}</p><p className="mt-3 text-sm text-body"><span className="font-bold">Reason:</span> {report.reason}</p><div className="mt-4 flex justify-end">{report.status !== "resolved" && <button onClick={() => void resolve(report.id)} className="rounded-lg bg-primary px-3 py-2 text-sm font-bold text-surface hover:bg-primary-hover">Mark resolved</button>}</div></article>) : <div className="rounded-xl border border-dashed border-border p-10 text-center text-muted">No message reports match this search.</div>}</div></div>;
}